# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'PKit/Core', :path => '../'
pod 'PKit/UI', :path => '../'


pod 'MJRefresh', '~> 3.2.0'
pod 'SnapKit', '~> 4.2.0'

end
