# Uncomment the next line to define a global platform for your project

inhibit_all_warnings!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '9.0'
pod 'PKit/Core', :path => '../'
pod 'PKit/UI', :path => '../'
pod 'PKit/Util', :path => '../'


pod 'MJRefresh', '~> 3.2.0'
pod 'SnapKit', '~> 4.2.0'

end

target 'Example-Command' do
  platform :osx, '11.0'
  pod 'PKit/JSON', :path => '../'
end
